import { Router } from 'express';
import { requireChannelMember } from '../middleware/workspace';
import * as channel from '../controllers/channelController';

const router = Router();
router.get('/:workspaceId',                           channel.list);
router.post('/',                                      channel.create);
router.patch('/:channelId/archive',                   channel.archive);
router.get('/:channelId/members',     requireChannelMember('channelId'), channel.getChannelMembers);
router.post('/:channelId/members',    requireChannelMember('channelId'), channel.addMember);
router.delete('/:channelId/members/:userId', requireChannelMember('channelId'), channel.removeMember);
router.get('/messages/:channelId',  requireChannelMember('channelId'), channel.getMessages);
router.post('/messages',                              channel.sendMessage);
router.patch('/messages/:id',                         channel.editMessage);
router.delete('/messages/:id',                        channel.deleteMessage);
router.get('/messages/:channelId/thread/:messageId',  requireChannelMember('channelId'), channel.getThreadReplies);
router.post('/messages/:messageId/share',             channel.shareMessage);
router.get('/messages/:messageId/reactions',          channel.getReactions);
router.post('/messages/:messageId/reactions',         channel.toggleReaction);
export default router;
export { setIo } from '../controllers/channelController';
